### ISSUE TITLE
Add support to sound null safety

### ISSUE THREAD

**Issue by unalone** [dart-lang/intl_translation#118] opened 2020-11-05 02:15 UTC
When using sound null safety, this the Localizations.of method will return a LocalizeStrings? result, so, we should add some code like this:

static LocalizeStrings? of(BuildContext context) {
    return Localizations.of<LocalizeStrings>(context, LocalizeStrings);
}

then, intl_translation:extract_to_arb and intl_translation:generate_from_arb will report error like:

Error in parsing lib/src/localize_strings.dart, no messages extracted.
Unhandled exception:
Invalid argument(s): Parsing errors in lib/src/localize_strings.dart
#0      MessageExtraction._parseCompilationUnit (package:intl_translation/extract_messages.dart:117:7)
#1      MessageExtraction.parseContent (package:intl_translation/extract_messages.dart:102:14)
#2      MessageExtraction.parseFile (package:intl_translation/extract_messages.dart:87:12)
#3      main.<anonymous closure> (file:///Users/unalone/opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/intl_translation-0.17.10+1/bin/generate_from_arb.dart:113:33)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#6      main (file:///Users/unalone/opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/intl_translation-0.17.10+1/bin/generate_from_arb.dart:116:23)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255

**Comment by nt4f04uNd** [comment] 2020-11-18 15:21
Guess that's why I get an error building on latest Flutter master
```
Because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0 and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, intl_translation >=0.17.7 is incompatible with flutter_localizations from sdk.
```

**Comment by nt4f04uNd** [comment] 2020-11-27 15:08
please add, I cannot build my app on flutter head because of that

**Comment by larssn** [comment] 2020-12-01 09:57
@nt4f04uNd That's unrelated to null safety, your issue is: https://github.com/dart-lang/intl_translation/issues/114

**Comment by nt4f04uNd** [comment] 2020-12-01 10:04
@Iarssn the message clearly point out to what this issue is related and that are dependency bounds of the packages. I changed upper bound to be 0.17.1 and it's compiling for me now

**Comment by vadrian89** [comment] 2020-12-30 11:06
> @nt4f04uNd That's unrelated to null safety, your issue is: #114

Hello, I am having this same issue after updating to beta channel. 

I have tried adding 

```
dependency_overrides:
  analyzer: '0.40.6'
```
and 
```
dev_dependencies:
  analyzer: '0.40.6'
```

Yet I am having the same issue 
`.... depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.`

Upgrading to 0.17.0 intl packages gives me: 

`Because intl_translation 0.17.10+1 depends on intl >=0.15.3 <0.17.0 and no versions of intl_translation match >0.17.10+1 <0.18.0, intl_translation ^0.17.10+1 requires intl >=0.15.3 <0.17.0.`

Can you point me to what I am not understanding?

**Comment by larssn** [comment] 2020-12-30 11:08
It's most likely because you are on the beta channel.

I'd stay clear of anything but stable until nullability is fully done and on stable.

**Comment by vadrian89** [comment] 2020-12-30 11:14
The issue is that I have a demo of a web version, of an app, which I need to update because of a bug...and now I can't.

Any ideeas?

**Comment by larssn** [comment] 2020-12-30 11:17
Sorry no, then I can't help.

Maybe @davidmorgan can chip in any ideas?

**Comment by vadrian89** [comment] 2020-12-30 11:27
I managed to downgrade the flutter sdk on beta channel and it finally worked.
Thank you.

**Comment by Kedar-27** [comment] 2021-01-02 15:35
any eta? when this issue will be fixed

**Comment by nt4f04uNd** [comment] 2021-01-02 16:14
just fork the repo and change the version constant or use mine, it's working just fine
https://github.com/nt4f04uNd/intl_translation

then do
```yaml
dev_dependencies:
  intl_translation:
    git: 
      url: https://github.com/nt4f04uNd/intl_translation
```

not sure if this is needed
```dart
dependency_overrides:
  analyzer: 0.40.1
```

**Comment by aleksakrstic** [comment] 2021-03-05 11:37
With https://github.com/localizely/intl_utils package we extended this intl_translation package and with just released version 2.0.0 it supports Flutter 2.0 and null-safety.

The migrations is simple. You just use it with this command:
`flutter pub run intl_utils:generate`

**Comment by Miamoto-Musashi** [comment] 2021-03-12 12:31
any update?

**Comment by jimmyff** [comment] 2022-01-31 13:29
I believe I have the same issue. Since migrating a production app to null safety I can no longer run `intl_translation:generate_from_arb`, I get the following error:

```
> Executing task in folder esc_core: dart run intl_translation:generate_from_arb --output-dir=lib/src/l10n/messages --no-use-deferred-loading lib/src/l10n/messages.dart lib/src/l10n/arb/intl_*.arb <

Building package executable... (3.6s)
Built intl_translation:generate_from_arb.
Error in parsing lib/src/l10n/messages.dart, no messages extracted.
Unhandled exception:
Invalid argument(s): Parsing errors in lib/src/l10n/messages.dart
#0      MessageExtraction._parseCompilationUnit (package:intl_translation/extract_messages.dart:117:7)
#1      MessageExtraction.parseContent (package:intl_translation/extract_messages.dart:102:14)
#2      MessageExtraction.parseFile (package:intl_translation/extract_messages.dart:87:12)
#3      main.<anonymous closure> (file:///home/jimmyff/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.10+1/bin/generate_from_arb.dart:113:33)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#5      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#6      main (file:///home/jimmyff/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.10+1/bin/generate_from_arb.dart:116:23)
#7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
The terminal process "bash '-c', 'dart run intl_translation:generate_from_arb --output-dir=lib/src/l10n/messages --no-use-deferred-loading lib/src/l10n/messages.dart lib/src/l10n/arb/intl_*.arb'" terminated with exit code: 255.

Terminal will be reused by tasks, press any key to close it.

```

Is this issue still unresolved? It's been open for 15 months now... :worried:

**Comment by jimmyff** [comment] 2022-01-31 13:36
I am temporarily using this package until the official one is updated:
https://pub.dev/packages/intl_generator

Seems to be a drop in replacement.

**Comment by mosuem** [comment] 2022-11-04 13:04
Closing in favor of #165 .

**Closed by mosuem** 2022-11-04 13:04 UTC
