### ISSUE TITLE
It's incompatible with Flutter 2 released today

### ISSUE THREAD

**Issue by mbalmer** [dart-lang/intl_translation#134] opened 2021-03-03 19:20 UTC
The subject says it all.

**Comment by chavesgu** [comment] 2021-03-04 06:57
Flutter stable version is `2.0.0`
I think it's necessary to be compatible with stable version

**Comment by bangfalse** [comment] 2021-03-04 07:01
I have opened [#367](https://github.com/dart-lang/intl/issues/367) in the `intl` project asking the maintainers to either update this package or provide the supported alternative in the documentation of the `intl` package.

**Comment by ksheremet** [comment] 2021-03-04 10:24
A very hacky temporary workaround for this is, in `pubspec.yaml`:

```yaml
dependency_overrides:
  intl: "0.17.0"
```

This seems to compile, but use at your own risk.

**Comment by mbalmer** [comment] 2021-03-04 11:28
> A very hacky temporary workaround for this is, in pubspec.yaml:
> 
> dependency_overrides:
>   intl: "0.17.0"
> This seems to compile, but use at your own risk.
> 
This works for me, thanks for the hint.  Looking for a definitive solution nevertheless ;)

**Comment by bangfalse** [comment] 2021-03-04 17:38
Note that when using that workaround, the generated library is not null-safe and will generate an analyzer message when imported into a null-safe project:
```
info: The library 'package:ridiculous_widgets/l10n/messages_all.dart' is legacy, and should not be imported into a null safe library. (import_of_legacy_library_into_null_safe at [ridiculous_widgets] lib/loc.dart:7)
```

This will make the analyzer happy when looking at that project or a project which imports it, but when. you actually try to build the project you'll get an error:

```
ext/ridiculous_widgets/lib/l10n/messages_all.dart:30:14: Error: The value 'null' can't be returned from a function with return type 'MessageLookupByLibrary' because 'MessageLookupByLibrary' is not nullable.
 - 'MessageLookupByLibrary' is from 'package:intl/message_lookup_by_library.dart' ('/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/message_lookup_by_library.dart').
      return null;
             ^
ext/ridiculous_widgets/lib/l10n/messages_all.dart:60:36: Error: The value 'null' can't be returned from a function with return type 'MessageLookupByLibrary' because 'MessageLookupByLibrary' is not nullable.
 - 'MessageLookupByLibrary' is from 'package:intl/message_lookup_by_library.dart' ('/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/message_lookup_by_library.dart').
  if (actualLocale == null) return null;
                                   ^


FAILURE: Build failed with an exception.
```

**Comment by mbalmer** [comment] 2021-03-04 17:42
> Note that when using that workaround, the generated library is not null-safe and will generate an analyzer message when imported into a null-safe project:
> 

As it is only a workaround, I think we all agree that we wait for a swift (pun intended.. ) update of the package in question.

**Comment by bangfalse** [comment] 2021-03-04 17:55
I would argue it's not an actual workaround if one can't create a working build using it.

For a further workaround, I've added PR #125 to this repo as an override, which explicitly marks the generated files as being Dart 2.7 so they're treated as null-unsound:

```yaml
dependency_overrides:
  intl: ^0.17.0
  intl_translation:
    git:
      url: git://github.com/dart-lang/intl_translation.git
      ref: 1a18d5a676ce94918f486ef699cb479f7578fdb6
```

**Comment by unalone** [comment] 2021-03-05 07:04
so,  is this package dying? seems no one maintain this package anymore

**Comment by larssn** [comment] 2021-03-05 10:42
@davidmorgan Any status on this?

**Comment by davidmorgan** [comment] 2021-03-05 10:49
We have the null safe generator change internally but I didn't push it external yet--it needs a little more work because internal/external integrations are different--needs wiring for the "generate null safe" flag. Or we could force it always for this release? @natebosch WDYT please?

**Comment by larssn** [comment] 2021-03-05 10:51
I thought the whole point was that it always generates null safe code 🙂

**Comment by davidmorgan** [comment] 2021-03-05 10:53
If you would like to use the output with Dart 2.11, it will have to be not null safe :) need to figure out if that is a use case that needs supporting or if people will always use the older package version for that.

**Comment by larssn** [comment] 2021-03-05 10:55
> If you would like to use the output with Dart 2.11, it will have to be not null safe :) need to figure out if that is a use case that needs supporting or if people will always use the older package version for that.

Wouldn't it be a valid workaround for them to simply use an older version of `intl_translation`?

**Comment by davidmorgan** [comment] 2021-03-05 10:58
That is precisely the question I am asking.

**Comment by mbalmer** [comment] 2021-03-05 11:16
> 
> That is precisely the question I am asking.
> 
> 

In an ideal world, it would generate null safety code for a null safety project, non-null safety code otherwise.

In less ideal world, there would be a flag (as intl_translation must be called manually anyways?)

**Comment by aleksakrstic** [comment] 2021-03-05 11:28
Hi everybody,
With https://github.com/localizely/intl_utils package we extended this `intl_translation` package and just released version 2.0.0 that supports Flutter 2.0 and null-safety.

The migrations is simple. You just use it with this command:
`flutter pub run intl_utils:generate`

**Comment by tjarvstrand** [comment] 2021-03-05 14:51
Until this has been solved in a more generic way, perhaps an option would be to publish to builds of the package for different dart versions?

**Comment by ghenry** [comment] 2021-03-05 17:29
I'm here too :-)

`So, because SureVoIPTalk depends on both intl ^0.17.0 and intl_translation ^0.17.10+1, version solving failed.)`

on Flutter 2.0.1

**Comment by natebosch** [comment] 2021-03-05 17:50
> Or we could force it always for this release? @natebosch WDYT please?

I think we should take the following steps:

1. Make a patch release against the old version that adds a `// @dart=2.9`  language version marker in the files it generates to avoid trouble when the non-null safe generator is used in a null safe package.
2. Make a breaking change release that emits null safe code. Users should upgrade to the new version at the point that they are ready for null safe code.

Does that seem feasible?

**Comment by ghenry** [comment] 2021-03-05 21:46
> A very hacky temporary workaround for this is, in `pubspec.yaml`:
> 
> ```yaml
> dependency_overrides:
>   intl: "0.17.0"
> ```
> 
> This seems to compile, but use at your own risk.

Done this to move on to the next Flutter 2 upgrade/fix in my pubspec :-)

**Comment by davidmorgan** [comment] 2021-03-08 17:54
@natebosch that sounds reasonable.

**Comment by duy1998** [comment] 2021-03-10 15:41
> I would argue it's not an actual workaround if one can't create a working build using it.
> 
> For a further workaround, I've added PR #125 to this repo as an override, which explicitly marks the generated files as being Dart 2.7 so they're treated as null-unsound:
> 
> ```yaml
> dependency_overrides:
>   intl: ^0.17.0
>   intl_translation:
>     git:
>       url: git://github.com/dart-lang/intl_translation.git
>       ref: 1a18d5a676ce94918f486ef699cb479f7578fdb6
> ```

how to get '1a18d5a676ce94918f486ef699cb479f7578fdb6' ? thanks

**Comment by orestesgaolin** [comment] 2021-03-10 18:33
My personal suggestion is to consider using [new default Flutter i18n approach](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) that uses only arb files and regenerates Dart classes on `flutter pub get` or app build. We did it for our app and works fine.

**Comment by mbalmer** [comment] 2021-03-11 08:40
I switched to the new automated approach, it is actually a lot easier to maintain l10n this way.  Nor more manual manual message extraction and generation.  Obsoletes intl_translations completely, imho. Closing the issue now.

**Comment by mayouf** [comment] 2021-03-11 12:47
Hi @orestesgaolin @mbalmer 

Would you elaborate your answers pls ? What is the difference with old approach ?

**Comment by orestesgaolin** [comment] 2021-03-11 13:15
> Would you elaborate your answers pls ? What is the difference with old approach ?

Sure! In the new approach you:
- provide `generate` flag in `pubspec.yaml`
- provide `l10n.yaml` file with your translation configuration
- provide desired arb files e.g. `app_en.arb` and `app_pl.arb` 

and Flutter will automatically generate localization delegates to be used inside your Flutter app based on that during `flutter pub get` or building.

```dart
 import 'package:flutter/material.dart';
 import 'package:flutter_localizations/flutter_localizations.dart'; // important
 import 'package:flutter_gen/gen_l10n/app_localizations.dart'; // important

 class MyApp extends StatelessWidget {
   @override
   Widget build(BuildContext context) {
     return MaterialApp(
       localizationsDelegates: AppLocalizations.localizationsDelegates, // important
       supportedLocales: AppLocalizations.supportedLocales, // important
       home: MyHomePage(),
     );
   }
 }
```

I wrote [article about it](https://roszkowski.dev/2021/i18n-in-flutter/), but you can also check out [the official docs](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) or [full guide](https://flutter.dev/go/i18n-user-guide)

**Comment by mayouf** [comment] 2021-03-11 13:51
Hi @orestesgaolin ,

Amazing, I'll do my homework..I'll let people know if I can plus-value about this subject, when I finish to fix it

**Comment by mbalmer** [comment] 2021-03-11 13:56
The new approach is actually a lot easier to use and maintain.

**Comment by mayouf** [comment] 2021-03-11 14:45
I still have this issue : 
```
Because `MYAPP depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because MYAPP depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because acropolic depends on intl ^0.16.1, version solving failed.)
```

and here is my pubspec.yaml: 
```
name: MYAPP 
description: describe my app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
```

and this is my `flutter doctor`: 
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [version 10.0.19042.804], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.1)
[√] Connected device (3 available)

```

Is there something Im missing here ?

**Comment by mbalmer** [comment] 2021-03-11 14:53
> dependencies:
>   flutter:
>     sdk: flutter
>   flutter_localizations:
>     sdk: flutter
>   intl: ^0.16.1

Set this to" intl: any"

**Comment by mayouf** [comment] 2021-03-11 14:58
hi @mbalmer ,

YOUPIIIIII, that worked !!!  How come by the way ? What does "any" do ?

**Comment by mbalmer** [comment] 2021-03-11 14:59
> YOUPIIIIII, that worked !!! How come by the way ? What does "any" do ?
> 

"any" takes the version pinned by flutter_localizations.

**Comment by mayouf** [comment] 2021-03-12 14:24
Hi here,

I want to warn people that the [new default Flutter i18n approach](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) (recommended by @mbalmer) works well...

**WARNING for Android Studio**

For people coding on Android Studio like me, there is strange behavior.

When we generate the `.dart_tool`, it does not appear in Android Studio, even if the folder is correctly generated and found in the project with a simple file explorer.

Then, there is no autocompletion available. And errors are reported by Android Studio, although the code works correctly when we start the app on emulator.

**HOW TO SOLVE IT** 
Not sure why it works, but I found an `.iml` file in the project root reporting folder to exclude. I removed the line reporting the .`dart_tool` folder.
And the folder became visible. (see below)
<img src="https://user-images.githubusercontent.com/5865600/110952567-aee31880-8346-11eb-8f26-df791a4187d1.png" width="400">


But maybe a more proper way exists....

**Comment by larssn** [comment] 2021-03-12 17:11
> Hi here,
> 
> I want to warn people that the [new default Flutter i18n approach](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) (recommended by @mbalmer) works well...
> 
> **WARNING for Android Studio**
> 
> For people coding on Android Studio like me, there is strange behavior.
> 
> When we generate the `.dart_tool`, it does not appear in Android Studio, even if the folder is correctly generated and found in the project with a simple file explorer.
> 
> Then, there is no autocompletion available. And errors are reported by Android Studio, although the code works correctly when we start the app on emulator.
> 
> **HOW TO SOLVE IT**
> Not sure why it works, but I found an `.iml` file in the project root reporting folder to exclude. I removed the line reporting the .`dart_tool` folder.
> And the folder became visible. (see below)
> <img alt="" width="400" src="https://user-images.githubusercontent.com/5865600/110952567-aee31880-8346-11eb-8f26-df791a4187d1.png">
> 
> But maybe a more proper way exists....

That is the fault of the tooling (i.e dart plugin). The same happens for the VSCode plugin.
You should report it over there instead.

**Comment by HansMuller** [comment] 2021-03-12 18:06
CC @shihaohong (FYI)

**Comment by MichaelM97** [comment] 2021-03-14 00:48
If the answer is to switch to the new i18n approach, then this package should be marked as `discontinued` with a message in the `README` explaining why

**Comment by kevin-lot** [comment] 2021-03-15 19:54
> I switched to the new automated approach, it is actually a lot easier to maintain l10n this way. Nor more manual manual message extraction and generation. Obsoletes intl_translations completely, imho. Closing the issue now.

Guys, you mixed up Flutter and Dart.
Some other projects without Flutter need intl_translation, eg AngularDart.

**Comment by gehad-ahmed-mohamed** [comment] 2021-03-25 05:10
adding this to my pubspec.yaml file fixed the problem

```
dependency_overrides:
  intl: ^0.17.0
  args: ^2.0.0
  petitparser: ^4.0.2
  analyzer: ^1.3.0
```

**Comment by PieterHartzer** [comment] 2021-03-26 01:16
> > Would you elaborate your answers pls ? What is the difference with old approach ?
> 
> Sure! In the new approach you:
> 
>     * provide `generate` flag in `pubspec.yaml`
> 
>     * provide `l10n.yaml` file with your translation configuration
> 
>     * provide desired arb files e.g. `app_en.arb` and `app_pl.arb`
> 
> 
> and Flutter will automatically generate localization delegates to be used inside your Flutter app based on that during `flutter pub get` or building.
> 
> ```dart
>  import 'package:flutter/material.dart';
>  import 'package:flutter_localizations/flutter_localizations.dart'; // important
>  import 'package:flutter_gen/gen_l10n/app_localizations.dart'; // important
> 
>  class MyApp extends StatelessWidget {
>    @override
>    Widget build(BuildContext context) {
>      return MaterialApp(
>        localizationsDelegates: AppLocalizations.localizationsDelegates, // important
>        supportedLocales: AppLocalizations.supportedLocales, // important
>        home: MyHomePage(),
>      );
>    }
>  }
> ```
> 
> I wrote [article about it](https://roszkowski.dev/2021/i18n-in-flutter/), but you can also check out [the official docs](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) or [full guide](https://flutter.dev/go/i18n-user-guide)

There is a shortcoming to that way which lead me down the path of intl_translation, and then got me stuck here.  You can't handle dynamic values. eg. `AppLocalizations.of(context).text(dynamic_value)`

The `dependency_overrides:` isn't working out for me either because the more I override the more break.

**Comment by rolandgeider** [comment] 2021-03-26 08:46
you can use dynamic values, just define them like this in the ARB file

```json
"hello": "Welcome {username}!",
"@hello": {
    "type": "text",
    "placeholders": {
      "username": {}
    }
  },
```

**Comment by PieterHartzer** [comment] 2021-03-26 11:38
> you can use dynamic values, just define them like this in the ARB file
> 
> ```json
> "hello": "Welcome {username}!",
> "@hello": {
>     "type": "text",
>     "placeholders": {
>       "username": {}
>     }
>   },
> ```

Perhaps I didn't explain the problem well enough.
Let's say we call an API which returns the a status codes:

- `UPCOMING`: transaction is anticipated but has not yet been attempted/allocated to be pending clearance (e.g. a scheduled direct debit)
- `PENDING`: transaction has been requested but does not yet impact the cleared balance
- `REVERSED`: transaction was requested but has since been reversed and effectively did not take place; it may still settle later

I would like the status to be translated (without using an if/case).  The ability to do it using `AppLocalizations.of(context).text("UPCOMING")` is required because I can use the result as `Text(AppLocalizations.of(context).text(state.Status))` and just place the status list in my translation files.  

en.arb
```
"PENDING" : "The transaction has been requested but does not yet impact the cleared balance"
```
af.arb
```
"PENDING" : "Die transaksie is aangevra maar het nog nie die huidige balans beïnvloed nie."
```


For a handful like this it's not as big a problem and I can use a hacky way around, but I am in a situation where I currently have 100 values returned and they will only grow with every release (quiz app's questions and answers).

**Comment by sammy44nts** [comment] 2021-03-31 18:54
> I switched to the new automated approach, it is actually a lot easier to maintain l10n this way. Nor more manual manual message extraction and generation. Obsoletes intl_translations completely, imho. Closing the issue now.

I use the [l18n](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) automated approach to retrieve the translated strings from the .arb but how to generate the .arb files without `flutter pub run intl_translation:extract_to_arb --output-dir=lib/l10n lib/main.dart` @mbalmer ? @cufbas

**Comment by sammy44nts** [comment] 2021-03-31 20:57
Found a workaround! See: https://github.com/dart-lang/intl/issues/367#issuecomment-811455527

**Comment by dotdoom** [comment] 2021-04-02 16:21
@davidmorgan @mit-mit since this is still unresolved could any of you unmark this as closed please?
This issue is starting to collect duplicates.

**Comment by stuartmorgan** [comment] 2021-04-08 20:34
All the discussion here is specifically about null safety; is there a reason you can't do a bugfix release in the short term that updates the `intl` dependency to 0.17 to address the fact that this is preventing people from updating to Flutter 2 at all (regardless of null safety)?

**Comment by ccadieux** [comment] 2021-04-09 19:59
Thanks for re-opening. I tried to use the new way of doing l10n but it does not work for our use case. One thing we had done is create a class that pulled out all the dependencies that require dart:ui from AppLocalizations. This way we could use the localization in our integration tests. Using the new approach still uses dependencies that require dart:ui so breaks all our usage in integration tests. 

Not having to use the dependency_overrides would be nice.

**Comment by edblocker** [comment] 2021-04-28 09:20
So this is `discontinued `?

**Comment by markovicdenis** [comment] 2021-04-30 19:10
> So this is `discontinued `?

Wondering too. This was a much better way than the new approach by the flutter team. As far I understand the new approach, we are supposed to write the arb files ourselves first? This package and it's approach makes more sense to me.

**Comment by mbalmer** [comment] 2021-05-01 09:13
> Am 30.04.2021 um 21:11 schrieb markovicdenis ***@***.***>:
> 
> ﻿
> So this is discontinued ?
> 
> Wondering too. This was a much better way than the new approach by the flutter team. As far I understand the new approach, we are supposed to write the arb files ourselves first? This package and it's approach makes more sense to me.
> 

Actually I switched all my projects to the new way, and I love it. I find it easier to maintain, one single file per language an manual extraction/generation.

As for the actual message translation, we use weblate, fwiw.

**Comment by jaumard** [comment] 2021-05-04 14:41
Guys... the new way is basically writing ARB files manually ?? Really!??? There is no way it is a safe way to do translations for bigs and/or complex projects... 
Is a null safety version of intl_translation will arrive soon ? Or is it still even maintained. Because by reading the thread here I'm a bit afraid I'll have to find a new solution for my translations, as the official way is just a joke. 

Is there any workaround until a version is in pub ? Because all the one above didn't worked for me

**Comment by yathit** [comment] 2021-05-05 05:30
The main issue with the new approach is that resulting translation could not be shared across multiple package. In our use case, we have base translation into base flutter package and shared to dependent packages.

**Comment by markovicdenis** [comment] 2021-05-07 11:06
> Is there any workaround until a version is in pub ? Because all the one above didn't worked for me

Well, you could use this package for code generation `https://github.com/localizely/intl_utils`. Sadly I didn't see support for arb extraction in their readme.

**Comment by jaumard** [comment] 2021-05-07 11:25
Yeah I ask them and they don't support ARB extraction, and that's a part I need :(

**Comment by mbalmer** [comment] 2021-05-07 11:33
FWIW, weblate.org work like a charm with ARB files.

**Comment by markovicdenis** [comment] 2021-05-07 11:39
> Yeah I ask them and they don't support ARB extraction, and that's a part I need :(

I was thinking about writing my own arb extraction script. This would be so much easier for me if ARB was JSON and if dart was node...

**Comment by jaumard** [comment] 2021-05-07 11:42
> I was thinking about writing my own arb extraction script. This would be so much easier for me if ARB was JSON and if dart was node...

ARB is just JSON :) it add metadata but they are optional. But it still plain/valid JSON file.

**Comment by markovicdenis** [comment] 2021-05-07 11:47
> > I was thinking about writing my own arb extraction script. This would be so much easier for me if ARB was JSON and if dart was node...
> 
> ARB is just JSON :) it add metadata but they are optional. But it still plain/valid JSON file.

I was thinking about comparing my existing ARB files with the new generated, and making sure I don't overwrite the already translated ones. I don't know if this feature was supported by this library.. I had to do this manually, when this library was still working.

**Comment by jaumard** [comment] 2021-05-17 15:36
> We have the null safe generator change internally but I didn't push it external yet--it needs a little more work because internal/external integrations are different--needs wiring for the "generate null safe" flag. Or we could force it always for this release? @natebosch WDYT please?

@davidmorgan @natebosch any schedule to have this please ? Or news :) would be nice

**Comment by jaumard** [comment] 2021-05-19 11:30
Hey people, I have started a fork and start migrating to null safety, so far it compile but doesn't work yet (some tests are failing), I could use some help so let's do that together :D 
Fork is here: https://github.com/kiwi-bop/intl_translation

**Comment by jaumard** [comment] 2021-05-21 12:58
So good news and bad news :) 

On my side the project is migrated and generate null safe code now, I'm able to generate ARB from dart and them generate null safe dart from ARB for my project. So I'm unlock and can move forward :)

The project have still failing tests and I don't find how to fix them... I any of you want to give it a try please do the error message is:

```
../../.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/intl.dart:162:30: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
          Map<String, Object>? examples,
                             ^
../../.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/intl.dart:163:17: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
          String? locale,
                ^
../../.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/intl.dart:164:17: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
          String? name,
                ^
../../.pub-cache/hosted/pub.dartlang.org/intl-0.17.0/lib/intl.dart:165:23: Error: Null safety features are disabled for this library.
Try removing the package language version or setting the language version to 2.10 or higher.
          List<Object>? args,
                      ^
exitCode=254
package:test_api                                            expect
test/message_extraction/message_extraction_test.dart 148:5  checkResult
===== asynchronous gap ===========================
dart:async                                                  Future.then
test/message_extraction/message_extraction_test.dart 79:10  main.<fn>

Expected: <0>
  Actual: <254>

```

If you want to use my fork please use:
```
intl_translation:
    git:
      url: git@github.com:kiwi-bop/intl_translation.git
```

**Comment by alan-knight** [comment] 2021-05-21 15:54
Not sure of the details, but that test spawns another Dart executable to run the extraction. It appears that it might be spawning an old version, or one that's missing the option to allow null-safety. The test is painful to debug, because it copies the files to a temp directory and runs various steps there. You can run the debug.sh script in the test/message_extraction directory to generate the files locally (but then you have to clean them up again before committing). But that makes it easier to debug. When I do that I get different errors, some null-safety issues in the generated code.

You might also consider just defaulting to the json generated format. It's much simpler, so it would be less work to debug the generated code, and it's easier on the compiler. That's particularly notable with dart2js, but probably makes a difference even with the VM. Internally at Google we defaulted to that, but I never changed the external default.

**Comment by jaumard** [comment] 2021-05-21 16:14
Thanks  @alan-knight for `debug.sh` tips, because it's indeed a nightmare to debug ^^ I have fixed of null safety generation issues, I didn't see those because I don't use json format so I wasn't migrated. 
 
> but that test spawns another Dart executable to run the extraction

Yeah that what causes trouble apparently, but I don't understand how it can spawn a dart version that is not null safe by default...

I have printed the command the is spawned:
```
Run process: /Users/jaumard/flutter/bin/cache/dart-sdk/bin/dart [/Users/jaumard/StudioProjects/intl_translation/bin/extract_to_arb.dart, --output-dir=/var/folders/60/55ytqsy93lg8jhh4tl7n0mzc0000gn/T/message_extraction_testX7S9aA, --suppress-warnings, --sources-list-file, /var/folders/60/55ytqsy93lg8jhh4tl7n0mzc0000gn/T/message_extraction_testX7S9aA/dart_list.txt]
```
And this dart is the last stable one `Dart SDK version: 2.13.0 (stable) ` so it should be null safe by default. I have tried to run that command manually on the folder, and that worked no errors at all... That is really weird

**Comment by alan-knight** [comment] 2021-05-21 19:31
I think the problem is that the Dart executable wants to get language version information on dependencies from the package. The code that's copied over to a temp directory isn't in a package, so it can't find anything, and defaults to pre-non-nullable by default. If I copy over the .dart_tool directory from intl_translation into that temporary directory then it works. Well, actually it starts failing by telling me there are null-safety violations, which counts as working for this purpose.

So I think you would have to either 
  - Put a pubspec.yaml into that test directory and also run an explicit pub in it as part of the test.
  - Copy over a .dart_tool/package_config.json. The main package one would probably work, or you could make a more limited one for just that test directory.

**Comment by jaumard** [comment] 2021-05-22 06:06
ha ha I think about that to be the root cause, but I check the doc and it say 2.13 is null safe by default so I didn't follow up on that ^^ I'll do that and fix the remaining errors. 
Thanks for your help

**Comment by jaumard** [comment] 2021-05-22 07:04
@alan-knight I now copy a pub spec and run pub get as part of the tests, I saw the null safety error you mention and fixed it but only by testing manually on the temp dir. But after I fix it I got the same error message saying it's not null safe and I should enable it... But now there is a pubspec and  a .dart_tools so it doesn't make any sens to still have that error. Really lost with that lol I'll keep digging more

**Comment by jaumard** [comment] 2021-05-22 19:01
Finally got it working!!! All test are green :) thanks @alan-knight for your help!

**Comment by jaumard** [comment] 2021-05-22 19:11
PR is done, https://github.com/dart-lang/intl_translation/pull/144 
Not sure if it will be accepted or not as it's unclear the status of the package, I might publish this on my side if needed

**Comment by alan-knight** [comment] 2021-05-24 14:12
Nice! Another thing you might look at is integrating with https://github.com/jamesblasco/intl_translation_format 

That's something @jamesblasco did last year as part of GSOC that has pluggable translation formats (e.g. adds XLIFF) and generated code, and lets you add to that without needing to modify or extend intl_translation. That way you might get around the issue of Flutter pinning versions.

**Comment by jaumard** [comment] 2021-05-26 06:47
I've published it on pub under `intl_generator` for the one eager to move on :) 
Also working on a new package called `intl_flavors` that integrate with build_runner instead of a dedicated command. And also help you with translation flavors if you need them. It take by the default flavor per locale and you can override sentences you need by flavor. Don't hesitate to check it out even if it's quite early so far by should cover basic cases. Any feedback would be welcome :)

**Comment by sanekyy** [comment] 2021-08-22 05:38
Any news?

**Comment by TriptSharma** [comment] 2021-09-19 21:37
Unable to generate dart files for .arb files.
Receiving `Oops; flutter has exited unexpectedly: "Null check operator used on a null value".`

I think it's because of the null safety issue. Is there any solution yet

**Comment by TriptSharma** [comment] 2021-10-10 09:09
> 
> 
> Use https://pub.dev/packages/intl_generator

Thanks, will give this a try.

**Closed** 2022-12-02 07:34 UTC
Labels: bug, Priority-High
