### ISSUE TITLE
intl_translation >=0.17.7 depends on old version of package intl 

### ISSUE THREAD

**Issue by shic** [dart-lang/intl_translation#136] opened 2021-03-10 16:52 UTC
These are the packages that  we are using.

```
dependencies:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  json_serializable: ^4.0.2
  intl_translation: ^0.17.10+1

```

Got error

```
Running "flutter pub get" in leopard...                         

Because intl_translation >=0.17.7 depends on intl >=0.15.3 <0.17.0 and leopard depends on intl ^0.17.0, intl_translation >=0.17.7 is forbidden.
So, because leopard depends on intl_translation ^0.17.10+1, version solving failed.
pub get failed (1; So, because leopard depends on intl_translation ^0.17.10+1, version solving failed.)
Process finished with exit code 1
```

**Comment by CaleyD** [comment] 2021-03-10 17:07
I think this is a duplicate of https://github.com/dart-lang/intl_translation/issues/134

**Comment by dotdoom** [comment] 2021-04-02 16:19
It is indeed, and #134 is closed now without providing options.

**Comment by patthipati** [comment] 2021-05-17 11:52
![Capture](https://user-images.githubusercontent.com/8288143/118484077-71c74800-b734-11eb-8db3-1a23e24339d9.PNG)

I'm also facing the same issue.

**Comment by patthipati** [comment] 2021-05-18 09:32
any Update

**Comment by erlandvr** [comment] 2021-06-07 14:20
Use this package instead. It does the same but is null safe.

**Comment by mosuem** [comment] 2022-11-04 13:15
Closing in favor of #165 .

**Closed by mosuem** 2022-11-04 13:15 UTC
