### ISSUE TITLE
Migrate intl_translation to build

### ISSUE THREAD

**Issue by dotdoom** [dart-lang/intl_translation#59] opened 2019-03-30 09:21 UTC
[`package:build`](https://pub.dartlang.org/packages/build) offers a uniform, automated way of building artifacts and source files. It also has a "watch" option which allows to update generated files seamlessly.

Would be beneficial to support build instead of memorizing (and amending the CI instructions with) pub commands. If dependency on `build` is undesirable, something like `intl_build` can be published as a separate package.

**Comment by dotdoom** [comment] 2019-03-30 09:25
Might be a duplicate of #32 but I don't know what the new build system is.

**Comment by kevmoo** [comment] 2019-03-31 06:59
Duplicate of #32 

`package:build` == "new build system"

**Closed by kevmoo** 2019-03-31 06:59 UTC
